### ISSUE TITLE
Certificate required to deploy locally

### ISSUE THREAD

**Issue by Mathieu265** [Orckestra/BetterRetail#28]
I see in the readme that i need a certificate (.develop.orckestra.local) to run the install.ps1. I tried to find it in the repo without luck. Any clues where i could find the certificate ?

**Comment by dabitbol** [comment]
Hi Mathieu,
Thanks for bring this up. Usually Orckestra can provide that certificate for customers and partners. In your case, you have 2 options:

1. Open a ticket to ask for one
2. Use your own certificate and change line 241 in install.cake for the install to use for the installation process.
