### ISSUE TITLE
Error 500 on https://composer-c1-betterretail.develop.orckestra.cloud/Composite/top.aspx

### ISSUE THREAD

**Issue by Mathieu265** [Orckestra/BetterRetail#32]
After running the _.\Install.ps1 -env=int_ i get a loading screen and some console error.
![image](https://user-images.githubusercontent.com/6610671/85136143-331bcb80-b20d-11ea-9e7b-c4c04858cadf.png)

Here are my configs:
_**parameters.json**_
```
{
  "ocs-cm-hostName": "",
  "ocsAuthToken": "",

  "em-branch": "4.9.0",
  "adminName": "",
  "adminPassword": "",
  "adminEmail": "build-bot@orckestra.com",

  "C1Url": "https://github.com/Orckestra/C1-CMS-Foundation/releases/download/v6.9/C1.CMS.6.9.zip",

  "websiteSuffix": "{{new System.IO.DirectoryInfo(rootPath).Name}}",
  "websiteName": "composer-c1-{websiteSuffix}.develop.orckestra.cloud",
  "websiteUrl": "https://{websiteName}",

  "setupDescription": "{{$\"{rootPath}/build/configuration/SetupDescription.xml\"}}",
  "setupDescriptionSecondary": "{{$\"{rootPath}/build/configuration/SetupDescriptionSecondary.xml\"}}",
  "baseCulture": "en-CA",
  "occ-hostName": "xxxx",
  "serviceBus-keyName": "xxxx",
  "serviceBus-key": "xxxx",
  "serviceBus-topicPrefix": "xxxx"
}
```

_**parameters.int.json**_
```
{
  "environments":{
    "int": {
      "adminName": "admin",
      "adminPassword": "123456",
      "ocs-cm-hostName": "ocs-cm-dev-localdeployment",
      "ocsAuthToken": ""
    }
  }
}
```

**Comment by Mathieu265** [comment]
After further investigation it look like application think its in prod mode and is looking for timestamped files while the files i have do not have a time stamp.

Here is what i get when i click the error from top.aspx in my chrome console
![image](https://user-images.githubusercontent.com/6610671/85294067-32cd3b80-b46c-11ea-83ff-0dbe9e236c3f.png)

In the screenshot we see the error where some of the files are missing and here is what i have when i browse to **_C:\Users\xxxx\Desktop\CDMV\BetterRetail\deployment\Website\Composite\scripts\compressed_**
![image](https://user-images.githubusercontent.com/6610671/85294396-935c7880-b46c-11ea-9a52-ba8471be2ca2.png)

The files are there but not timestamped, also in the first screenshot we see this line
```
Application.hasExternalConnection = true;Application.isDeveloperMode = false;Application.isLocalHost = false;Application.isOnPublicNet = true;
```
This lead me to believe that the application think that it's running in prod mode since _isDeveloperMode = false_ and _isLocalHost = false_.

**Comment by Mathieu265** [comment]
Also while looking at the chrome console i found that the files that were not a problem were the one that were visible on the left side
![image](https://user-images.githubusercontent.com/6610671/85427518-da6c6b80-b549-11ea-837d-ddf9779f1407.png)

For example **branding.css** is found on the left and has no problem loading which make total sense but im having a hard time figuring out why the other depencies didnt make it.

**Comment by napernik** [comment]
Hi @Mathieu265 

From the looks of it - IIS isn't serving static files (*.css,*.js, etc.)
Likely - this feature isn't turned on:

![image](https://user-images.githubusercontent.com/1391705/85532985-6ea10600-b610-11ea-9231-aa076c98d9d1.png)

I recommend enabling all the features, marked as "checked" on the screenshot as well.

**Comment by Mathieu265** [comment]
On my side it was a configuration error. The repo folder need to have some permission setup
![image](https://user-images.githubusercontent.com/6610671/86131928-4142d500-bab4-11ea-90e7-94ec9303dd95.png)
Not sure if **IIS_IUSRS** needs to be there if you have **composer-c1-BetterRetail.develop.orckestra.cloud**
